/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author labuc9806
 */
public class MultipleChoicefrm extends javax.swing.JFrame {

    /**
     * Creates new form MultipleChoicefrm
     */
    public MultipleChoicefrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        q1lbl = new javax.swing.JLabel();
        q2lbl = new javax.swing.JLabel();
        q3lbl = new javax.swing.JLabel();
        q4lbl = new javax.swing.JLabel();
        q5lbl = new javax.swing.JLabel();
        ansinputlbl = new javax.swing.JLabel();
        ansinputlbl2 = new javax.swing.JLabel();
        ansinputlbl3 = new javax.swing.JLabel();
        ansinputlbl4 = new javax.swing.JLabel();
        ansinputlbl5 = new javax.swing.JLabel();
        a1lbl = new javax.swing.JLabel();
        b1lbl = new javax.swing.JLabel();
        c1lbl = new javax.swing.JLabel();
        d1lbl = new javax.swing.JLabel();
        ans1txt = new javax.swing.JTextField();
        a2lbl = new javax.swing.JLabel();
        b2lbl = new javax.swing.JLabel();
        c2lbl = new javax.swing.JLabel();
        d2lbl = new javax.swing.JLabel();
        ans2txt = new javax.swing.JTextField();
        a3lbl = new javax.swing.JLabel();
        b3lbl = new javax.swing.JLabel();
        c3lbl = new javax.swing.JLabel();
        d3lbl = new javax.swing.JLabel();
        ans3txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        q1lbl.setText("Question 1 : An interpreter does everything except... ");

        q2lbl.setText("Question 2 : The number -98.556 can be stored as a :");

        q3lbl.setText("Question 3 : What source package must you add in order to create a GUI?");

        q4lbl.setText("Question 4");

        q5lbl.setText("Question 5");

        ansinputlbl.setText("Answer: ");

        ansinputlbl2.setText("Answer:");

        ansinputlbl3.setText("Answer:");

        ansinputlbl4.setText("Answer :");

        ansinputlbl5.setText("Answer :");

        a1lbl.setText("A. Translate program one line at a time");

        b1lbl.setText("B. Generates an error message after scanning the entire program ");

        c1lbl.setText("C.Is used by programming languages like Python and Ruby");

        d1lbl.setText("D. Takes less time to analyze source code");

        ans1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans1txtActionPerformed(evt);
            }
        });

        a2lbl.setText("A. Integer");

        b2lbl.setText("B. String ");

        c2lbl.setText("C. Boolean");

        d2lbl.setText("D. Double");

        ans2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans2txtActionPerformed(evt);
            }
        });

        a3lbl.setText("A. Java Interface");

        b3lbl.setText("B. Java Panel Form");

        c3lbl.setText("C. Java Frame Form");

        d3lbl.setText("D. Java Class");

        ans3txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans3txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1lbl)
                            .addComponent(b1lbl)
                            .addComponent(c1lbl)
                            .addComponent(a1lbl)
                            .addComponent(d1lbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ansinputlbl)
                                .addGap(18, 18, 18)
                                .addComponent(ans1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(q2lbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ansinputlbl2)
                        .addGap(18, 18, 18)
                        .addComponent(ans2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(a2lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(c2lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d2lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b2lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(q3lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ansinputlbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ans3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(a3lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b3lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(c3lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d3lbl))
                    .addComponent(q4lbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(ansinputlbl5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(q5lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ansinputlbl4)))
                .addContainerGap(521, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(q1lbl)
                .addGap(14, 14, 14)
                .addComponent(a1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d1lbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansinputlbl)
                    .addComponent(ans1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(q2lbl)
                .addGap(18, 18, 18)
                .addComponent(a2lbl)
                .addGap(4, 4, 4)
                .addComponent(b2lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d2lbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansinputlbl2)
                    .addComponent(ans2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(q3lbl)
                .addGap(18, 18, 18)
                .addComponent(a3lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b3lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(d3lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansinputlbl3)
                    .addComponent(ans3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(q4lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ansinputlbl5)
                .addGap(29, 29, 29)
                .addComponent(ansinputlbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q5lbl)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ans1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans1txtActionPerformed

    private void ans2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans2txtActionPerformed

    private void ans3txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans3txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans3txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoicefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoicefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoicefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoicefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoicefrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1lbl;
    private javax.swing.JLabel a2lbl;
    private javax.swing.JLabel a3lbl;
    private javax.swing.JTextField ans1txt;
    private javax.swing.JTextField ans2txt;
    private javax.swing.JTextField ans3txt;
    private javax.swing.JLabel ansinputlbl;
    private javax.swing.JLabel ansinputlbl2;
    private javax.swing.JLabel ansinputlbl3;
    private javax.swing.JLabel ansinputlbl4;
    private javax.swing.JLabel ansinputlbl5;
    private javax.swing.JLabel b1lbl;
    private javax.swing.JLabel b2lbl;
    private javax.swing.JLabel b3lbl;
    private javax.swing.JLabel c1lbl;
    private javax.swing.JLabel c2lbl;
    private javax.swing.JLabel c3lbl;
    private javax.swing.JLabel d1lbl;
    private javax.swing.JLabel d2lbl;
    private javax.swing.JLabel d3lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel q1lbl;
    private javax.swing.JLabel q2lbl;
    private javax.swing.JLabel q3lbl;
    private javax.swing.JLabel q4lbl;
    private javax.swing.JLabel q5lbl;
    // End of variables declaration//GEN-END:variables
}
